services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dicescore
      POSTGRES_PASSWORD: dicescore
      POSTGRES_DB: dicescore
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
